### ISSUE TITLE
PVC restore fails due to "Snapshot is not Ready"

### ISSUE THREAD

**Issue by betta1** [vmware-tanzu/velero-plugin-for-csi#1]
I installed the velero-csi-plugin and followed the steps to backup and restore the demo app. I have the ebs-csi-driver up and running on my k8s on AWS. PV snapshots via the velero csi plugin work as expected, however PVC restores from the csi snapshots fail since volume snapshots are not ready. This causes the pod to be stuck in pending state:

"Warning  ProvisioningFailed    18s (x6 over 47s)  ebs.csi.aws.com_ebs-csi-controller-0_178686e9-ae29-11e9-af00-6e03acfc45b2  failed to provision volume with StorageClass "ebs-sc": error getting snapshot handle for snapshot velero-ebs-claim-qrtd4: snapshot velero-ebs-claim-qrtd4 is not Ready"

$ velero restore create --from-backup demo-backup
    Restore request "demo-backup-20190724104629" submitted successfully.
    ...
$ kubectl get po -n demo
   NAME   READY   STATUS    RESTARTS   AGE
   app        0/1        Pending   0                 12m

$ kubectl describe pvc ebs-claim -n demo
Name:          ebs-claim
Namespace:     demo
StorageClass:  ebs-sc
Status:        Pending
.
.
.
Type     Reason                Age                From                                                                       Message
----     ------                ----               ----                                                                       -------
Normal   Provisioning          18s (x6 over 47s)  ebs.csi.aws.com_ebs-csi-controller-0_178686e9-ae29-11e9-af00-6e03acfc45b2  External provisioner is provisioning volume for claim "demo/ebs-claim"
Warning  ProvisioningFailed    18s (x6 over 47s)  ebs.csi.aws.com_ebs-csi-controller-0_178686e9-ae29-11e9-af00-6e03acfc45b2  failed to provision volume with StorageClass "ebs-sc": error getting snapshot handle for snapshot velero-ebs-claim-qrtd4: snapshot velero-ebs-claim-qrtd4 is not Ready
Normal   ExternalProvisioning  9s (x5 over 47s)   persistentvolume-controller                                                waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator

**Comment by nrb** [comment]
Thanks for the report @betta1. I will continue to test this with the new beta types and see if we can catch this.

**Comment by skriss** [comment]
xref https://github.com/vmware-tanzu/velero/issues/1799 (similar issue with legacy VolumeSnapshotters)

**Comment by ashish-amarnath** [comment]
@betta1 The issue was reported prior to the first release of this plugin.
Closing this issue. But, please try this in the latest release of the plugin, [`v0.1.2`](https://github.com/vmware-tanzu/velero-plugin-for-csi/releases/tag/v0.1.2), and re-open or reach out if you have more questions.
