### ISSUE TITLE
Handle scenario of 1: many relationship between VolumesnapshotClass and Provisioner.

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero-plugin-for-csi#17]
More info https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/16/files#r382658783

/assign

EDIT:
During backing up a PVC, backed by CSI, we need to choose a VolumeSnapshotClass to use for creating the VolumeSnapshots. This is done in the `util. GetVolumeSnapshotClassForStorageClass` function, where we pick the first VolumeSnapshotClass that has the same volume provider/driver name.
It is possible to have multiple VolumeSnapshotClasses for the same provider/driver with different values for other fields in the spec that need to be taken into consideration when choosing the VolumeSnapshotClass

**Comment by ashish-amarnath** [comment]
Based on discussion here https://github.com/kubernetes-csi/external-snapshotter/issues/273#issuecomment-599792099
volumesnapshotcontents are not intended to be linked to multiple volumesnapshot as they can have conflicting DeletionPolicies.
Closing this issue.

**Comment by skriss** [comment]
@ashish-amarnath the comment you linked to is about VolumeSnapshotContent to VolumeSnapshot, but this issue seems to be about VolumeSnapshotClass to Provisioner - am I missing something?

**Comment by skriss** [comment]
reopening for now to track, can re-close if appropriate.

**Comment by ashish-amarnath** [comment]
@skriss Thanks for re-opening this. You are right, this issue is about volumesnapshotclass and provider.
Added some comments in the code https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/42
I will add more description to the issue.

**Comment by sdodsley** [comment]
This is actually really important. As Velero requires that the `deletionPolicy` is `retain` this can cause issues with volumes that have snapshots unmanaged by Velero should there be only one volumesnapshotclass. This means that there will be more than one volumesnapshotclass per provider. 
Currently picking the first one requires careful planning of class names.  This is not intuitive (or well documented). 
There has to be a selector for the volumesnapshotclass to use for Velero.

**Comment by ashish-amarnath** [comment]
@sdodsley I've put up a PR#60 to address this issue.
