### ISSUE TITLE
reorganize repo structure

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero-plugin-for-csi#27]
The repo/package structure is a little weird right now. Currently we have:

```
github.com/vmware-tanzu/velero-plugin-for-csi/
    velero-csi-plugin/
        main.go
        <all other code>
```

I'd propose moving to something like either:

Option 1 - totally flat
```
github.com/vmware-tanzu/velero-plugin-for-csi/
    main.go
    <all other code>
```

Option 2 - main.go in the root, lib code inside `internal/`
```
github.com/vmware-tanzu/velero-plugin-for-csi/
    main.go
    internal/
        backup/
            <backup plugins>
        restore/
            <restore plugins>
```

Thoughts?

cc @nrb @ashish-amarnath @carlisia

**Comment by nrb** [comment]
I think I'd go with option 2 myself. I honestly can't remember why I started it down the path I did.

**Comment by skriss** [comment]
Yeah I'm 👍 to option 2. I think the current structure was probably initially copied from the plugin-example repo, which has a similarly weird structure - IIRC, I was the one who did the copying :)

**Comment by ashish-amarnath** [comment]
I will do the re-org once #19 is merged in.

**Comment by carlisia** [comment]
Yes, I like option 2 as well. 

I remember trying to do that when I was reorganizing the plugin code, but there were problems with the path/binary.

**Comment by skriss** [comment]
@ashish-amarnath those are both merged, so ready to go!

**Comment by ashish-amarnath** [comment]
Was working on that! Just didn't say I started
