### ISSUE TITLE
On restore, handle the scenario where the VSC+VS already exist in the cluster more gracefully

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero-plugin-for-csi#41]
Scenario: 
1. Deploy https://github.com/vmware-tanzu/velero/blob/master/examples/nginx-app/with-pv.yaml into a CSI-enabled Azure AKS cluster with a requested size of >= 1Gi.
1. Create a backup
1. Delete the nginx app (`kubectl -n nginx-example delete deploy,pvc --all`). **Note** that the full namespace is not deleted.
1. Observe that the VSC/VS created by the backup still exist
1. Restore the backup
1. Observe that:
    - a new, second statically-provisioned VolumeSnapshotContent is created
    - the restore logs a warning that the VolumeSnapshot could not be restored because it already exists in the cluster, **and** it's different than the backed-up version
    - the PVC is properly restored, from the existing VolumeSnapshot that's using the original VolumeSnapshotContent

I totally understand why this is happening, and the end result is that the PVC is still properly restored.

However, it would be very nice if we could detect the scenario where the VolumeSnapshot + VolumeSnapshotContent pair created by the backup still/already exist in the cluster and are properly linked to each other, so we don't need to create a second VSC *or* attempt to restore the VS. In this case, we just need to use that VS as the data source for the PVC.

**Comment by runzexia** [comment]
any updates? I also encountered this problem

**Comment by ashish-amarnath** [comment]
Here is my proposed solution:
If we detect that the `VolumeSnapshot`, that is being restored, already exists- regardless of whether or not it is linked to the expected `VolumeSnapshotContent`, then we skip the creation of the `VolumeSnapshotContent` for static linking and let the plugin return its input untouched. This will let Velero handle this as a restoration of an existing resource. 

The justification for ignoring the scenario where the `VolumeSnapshot` object exists but is linked to a different `VolumeSnapshotContent` object is: that change was performed outside of Velero and should not be overwritten.

I am going to put up a PR with this proposal if this is an acceptable solution.
@nrb Thoughts?

**Comment by nrb** [comment]
@ashish-amarnath So you're detecting only the `VolumeSnapshot`? I think that works if it exists and is pointing to a `VolumeSnapshotContent`, but would result in a bad state if the `VolumeSnapshot` existed but referenced a non-existent `VolumeSnapshotContent`.

Other than that case, I think your proposal makes sense.

**Comment by ashish-amarnath** [comment]
@nrb Yes if the existing `VolumeSnapshot` doesn't point to the expected `VolumesnapshotContent` it can result in a bad state. But that bad state would be caused by something outside of Velero, a user action maybe. I don't think Velero should attempt "fixing" it, which is the point I was trying to make.
