### ISSUE TITLE
restored VolumeSnapshotContents are always created with a deletion policy of "Delete"

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero-plugin-for-csi#43]
https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/master/internal/restore/volumesnapshot_action.go#L83

I *think* we want these to be created as "Retain", so that if the namespace is subsequently deleted, we don't inadvertently delete the snapshots - does that sound right? cc @ashish-amarnath 

Repro scenario is:
- create a backup
- delete the workload namespace
- restore from the backup
- delete the workload namespace
- attempt to restore again -- it'll fail because the actual storage snapshot got deleted in the previous step

**Comment by skriss** [comment]
Actually, I'm thinking we should copy the DeletionPolicy from the original VolumeSnapshotContent (we probably need to store it as an annotation during backup like the SnaphotClass/Handle). `Retain` makes sense for the Velero-created snapshots, but if we're restoring a non-Velero snapshot, then I'd think we want to keep whatever the original DeletionPolicy was.

Please check my thinking here.

**Comment by ashish-amarnath** [comment]
Rechecking some of my assumptions on this.

**Comment by ashish-amarnath** [comment]
@skriss Yes, what you are suggesting makes sense.

**Comment by ashish-amarnath** [comment]
@skriss Thanks for catching this bug for me. I've updated the PR #44
