### ISSUE TITLE
Github Actions should push images with `latest` tag

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero-plugin-for-csi#52]
Currently the github actions are setup to push images with tag `master` and a release github tag.

The actions should also push images with the `latest` tag to be consistent with images pushed from other velero repos

cc @skriss

**Comment by skriss** [comment]
:+1: 

See https://github.com/vmware-tanzu/velero/blob/master/hack/docker-push.sh for how this is handled with Travis today in Velero core. This will need to be adapted for GH Actions.
