### ISSUE TITLE
Use new API to identify if a volume is backed up using restic

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero-plugin-for-csi#58]
Use the `GetPodVolumesUsingRestic` API introduced in PR https://github.com/vmware-tanzu/velero/pull/2611

**Comment by stephbman** [comment]
From backlog meeting:

- ideal path: cut 1.5 release to make API available for CSI driver
- could add to main prior to 1.5 release if needed (requires some investigation)
