### ISSUE TITLE
when install velero with  EnableCSI,fail msg  CSI API group [snapshot.storage.k8s.io/v1beta1] was not found

### ISSUE THREAD

**Issue by lht2017** [vmware-tanzu/velero-plugin-for-csi#59]
**CMD: kubectl logs -f  pod/velero-5cf9ff89d9-ntblg  -n velero**
time="2020-06-12T07:11:41Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:177"
time="2020-06-12T07:11:41Z" level=info msg="Starting Velero server v1.4.0 (5963650c9d64643daaf510ef93ac4a36b6483392)" logSource="pkg/cmd/server/server.go:179"
time="2020-06-12T07:11:41Z" level=info msg="1 feature flags enabled [EnableCSI]" logSource="pkg/cmd/server/server.go:181"
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-pvc-backupper
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-volumesnapshot-backupper
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-volumesnapshotclass-backupper
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-volumesnapshotcontent-backupper
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-pvc-restorer
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-volumesnapshot-restorer
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-volumesnapshotclass-restorer
time="2020-06-12T07:11:41Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-csi kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/csi-volumesnapshotcontent-restorer
time="2020-06-12T07:11:41Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2020-06-12T07:11:41Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:367" namespace=velero
time="2020-06-12T07:11:44Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:396"
time="2020-06-12T07:11:44Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:430"
time="2020-06-12T07:11:44Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
time="2020-06-12T07:11:46Z" level=warning msg="Velero restic daemonset not found; restic backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:509"
time="2020-06-12T07:11:46Z" level=info msg="Starting controllers" logSource="pkg/cmd/server/server.go:585"
time="2020-06-12T07:11:46Z" level=info msg="Starting metric server at address [:8085]" logSource="pkg/cmd/server/server.go:593"
time="2020-06-12T07:11:47Z" level=fatal msg="**The 'EnableCSI' feature flag was specified, but CSI API group [snapshot.storage.k8s.io/v1beta1] was not found."** logSource="pkg/cmd/server/server.go:569"

**Comment by ashish-amarnath** [comment]
Hi @lht2017 The error indicates that you don't have the `v1beta1` snapshot API CRDs installed in your cluster. Please refer to instructions [here](https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/#how-do-i-deploy-support-for-volume-snapshots-on-my-kubernetes-cluster) for installing these CRDs.

**Comment by ashish-amarnath** [comment]
@lht2017 
I am closing this issue. Please feel free to reach out if you need further assistance in setting up CSI snapshotting in your cluster. I would also suggest referring to your CSI driver's installation document for setup instructions.
