### ISSUE TITLE
volumesnapshot DeletionPolicy actions is not same with doc

### ISSUE THREAD

**Issue by runzexia** [vmware-tanzu/velero-plugin-for-csi#62]
From doc:
https://velero.io/docs/main/csi/
```
VolumeSnapshotContents will have a DeletionPolicy of Retain for the life of the Velero backup in order to prevent them from being deleted on the storage system. When the Velero backup expires, the VolumeSnapshot objects will be deleted and the VolumeSnapshotContent objects will be updated to have a DeletionPolicy of Delete, in order to free space on the storage system.
```

From code 
https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/3d66b3b785d7721a6db457469ab1207faef60e4c/internal/backup/pvc_action.go#L116

change the code and  set VolumeSnapshotContents DeletionPolicy=Retain as default?

**Comment by ashish-amarnath** [comment]
@runzexia Thank you for raising this issue. Changing the code to use a different `DeletionPolicy` from what was set in the VolumeSnapshotClass would seem like overriding what the user set in the `VolumeSnapshotClass` which we don't want the plugin to do.
I've opened PR https://github.com/vmware-tanzu/velero/pull/2765 to clarify the docs.

**Comment by ashish-amarnath** [comment]
The PR is now merged.
Closing this issue.
