### ISSUE TITLE
rook-ceph rbd snapshot

### ISSUE THREAD

**Issue by itkh** [vmware-tanzu/velero-plugin-for-csi#66]
Does this plugin support rook-ceph RBD snapshot?
After testing with rook-ceph block pool storage, I found out that it works well with PVC snapshot.
However, snapshot data is not being uploaded to snapshot location storage (minio for my test).
what is VolumeSnapshotter plugin for csi? 
Is there any upload and download resources for this plugin?

**Comment by ashish-amarnath** [comment]
We have not tested this with specific providers. As long as the storage provider is CSI conformant you should be able to use the velero-plugin-for-csi.

About:
> However, snapshot data is not being uploaded to snapshot location storage (minio for my test).
what is VolumeSnapshotter plugin for csi?

The CSI snapshot APIs standardize volume snapshot operations across different providers. The velero-plugin-for-csi, uses these APIs to support volume snapshotting for all CSI conformant providers. These volume snapshots are not portable across volume providers and the snapshots are also managed by the storage providers. The snapshot data will not be stored in the backup storage location. The plugin supports backup and restores only. Uploading and downloading volume snapshots is not part of the upstream CSI spec and for that reason, there isn't a way to upload/download data using this plugin.

I am going to close this issue as your question has been answered. Feel free to reach out if you have more questions.
